### ISSUE TITLE
Windows: more consistent API

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/ProcessDoctor#4]
Currently, we rely on WMI events to list Windows processes. That API is good enough for most purposes, but it has a problem with consistency: if we only rely on process start/stop events, we may easily miss some processes.

Also, we don't show the processes started before the program startup.

I suggest that we consider using periodic requests to `CreateToolhelp32Snapshot`, or periodic WMI queries of the full process list.

`CreateToolhelp32Snapshot` has a downside that we won't be able to get the process' command line.

The latter I remember as being clunky, but this is yet to be checked :)

Also, if we migrate to WMI list queries instead of WMI events, we may easily miss some processes, and we don't want to miss any (we should properly register quick start+exit of a process, if possible).

**Comment by y0ung3r** [comment]
May I know the reason why you don't want to use `Process.GetProcesses()` along with WMI?

**Comment by ForNeVeR** [comment]
1. It has no hooks to observe the process startup and termination, we'd need to just invoke it quite often.
2. It provides no information about the process' command lines, and that's one of the most important things in the process manager.
3. I am quite sure it has no _snapshot_ semantics, i.e. it's theoretically possible that a process with the same id will be started and stopped during our enumeration of `Process.GetProcesses()` multiple times, wreaking all sorts of havoc.

**Comment by y0ung3r** [comment]
@ForNeVeR How about using `RxNet` to receive `WMI` events in `WmiProcessMonitor`? I think it would help to cover the code with tests, make the code readable and more flexible for further development of the project. What do you think?

**Comment by ForNeVeR** [comment]
I can't see how it would help, but I am not against trying that.

**Comment by y0ung3r** [comment]
@ForNeVeR Do you know anything about `PsSetCreateProcessNotifyRoutine` function? Should we consider using it?

**Comment by y0ung3r** [comment]
> `CreateToolhelp32Snapshot` has a downside that we won't be able to get the process' command line.

I also found that we probably just need to make additional requests to WinApi to get the command line. See [QueryFullProcessImageName](http://msdn.microsoft.com/en-us/library/windows/desktop/ms684919%28v=vs.85%29.aspx), [GetProcessImageFileName](http://msdn.microsoft.com/en-us/library/windows/desktop/ms683217%28v=vs.85%29.aspx), or [GetModuleFileNameEx](http://msdn.microsoft.com/en-us/library/windows/desktop/ms683198%28v=vs.85%29.aspx)

**Comment by ForNeVeR** [comment]
Would that require us to implement a Windows kernel driver? I do not want to dive into that, to be honest.
